修复Linux下面crontab环境无法正常执行的问题
rehiy/dnspod-shell pull request #127
Opened 2023-03-10 04:43 UTC by genezx

2023-03-10 05:32 UTC, rehiy commented
一旦这样指定路径，会导致很多/opt环境失效。你只需要把你的系统PATH设置下就可以的

2023-03-10 07:11 UTC, genezx commented
我知道可以改系统PATH，但是这么做不安全，为了安全起见最好手动指定ip的完整路径。/opt环境可以自己对照着改路径。

2023-03-10 08:07 UTC, Vigilans requested changes

2023-03-10 08:07 UTC, Vigilans commented on ardnspod
> +ip=/usr/sbin/ip
`ardnspod`作为用户不应该有自己改的需求的库文件，不可以只写死一个路径。

不说/opt的问题，仅在我的debian和archlinux系统上，`which ip`返回的结果都是`/usr/bin/ip`:
```
$ which ip                                                                                                                                                                                       
/usr/bin/ip
```
在alpine系统上，结果是：
```
$ which ip                                                                                                             ​
/sbin/ip
```
如果你想要`ip`命令使用绝对路径的话，你可以就几个可能常用的路径进行枚举搜索，并将其包装成一个类似`arLog`与`arRequest`的函数，或是`arIp6QueryUrl`这样的环境变量，使得用户能在`ddnspod.sh`中自定义，而非需要修改ardnspod：
https://github.com/rehiy/dnspod-shell/blob/afb27e3a757a384ff1f94374d2f5e00cd93bc3a7/ardnspod#L29-L76

2023-03-10 08:15 UTC, rehiy commented
这位同学遇到的问题是，非管理员用户无法使用 /usr/sbin 目录命令的问题。应该更换为管理员，或者在自己的配置文件中设置 `export PATH=$PATH:/usr/sbin:/usr/bin`，再或者ln这个命令到/usr/bin 。实际工作中，我遇到很多 ip 命令不在 /usr目录的。

2023-03-11 18:18 UTC, genezx commented
楼上大佬们说的有理，那要不就用环境变量自己配置吧，默认写成 debian 的路径。

2023-03-12 07:34 UTC, Vigilans commented on ardnspod
> +export arCmdIp
为了与以前保持兼容，这里`arCmdIp`应该至少使用`$(which ip)`作为默认值。

注释需要更详细点，名字可以考虑`arIproute2`之类的。

2023-03-12 07:34 UTC, Vigilans commented on ddnspod.sh
> +arCmdIp=/usr/bin/ip
这里应该像`arIp6QueryUrl`与`arErrCodeUnchanged`一样默认注释掉，并添加如`=$(which ip)`表示这是`arCmdIp` 的默认值。 注释也需要更详细一些（这个配置是做什么的，什么情况下用户需要改它）。

2023-03-12 10:47 UTC, genezx commented on ardnspod
> +export arCmdIp
名字我觉得这样就挺好的，arCmd表示命令，后面跟个命令名字就行了。

注释再详细点的话我不知道要写啥。

2023-03-12 10:49 UTC, genezx commented on ddnspod.sh
> +arCmdIp=/usr/bin/ip
这里默认不能注释掉呀，因为程序里面要用的，可以用 `$(which ip)` 做默认值。

2023-03-12 10:51 UTC, Vigilans commented on ardnspod
> +export arCmdIp
注释参考下面的`arIp6QueryUrl`与`arErrCodeUnchanged`：
https://github.com/rehiy/dnspod-shell/blob/f6a7b7df7eb1db859515398695c8000970221f10/ddnspod.sh#L10-L16

2023-03-12 10:51 UTC, Vigilans commented on ddnspod.sh
> +arCmdIp=/usr/bin/ip
那为什么下面的`arIp6QueryUrl`与`arErrCodeUnchanged`注释掉了，程序还是可以正常运行呢？

2023-03-12 10:52 UTC, genezx commented on ddnspod.sh
> +arCmdIp=/usr/bin/ip
哦，我知道你的意思了。

2023-05-24 14:11 UTC, closed without merging